version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./data:/data
      - ${THEME_DIR}:/var/www/html/wp-content/themes/dev-theme

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
